[package]
name = "holyhashmap"
version = "0.1.0"
authors = ["Jason White <jwhite@esri.com>"]

[dependencies]
serde = { version = "1", optional = true }
serde_test = { version = "1", optional = true }

[dev-dependencies]
quickcheck = "0.7"
rand = "0.5"
